using NLog;
using NUnit.Framework;
using Project_Euler.Problem0002;

namespace ProjectEuler.Test;

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class Problem0002Test
{
    private static readonly Logger Logger = LogManager.GetCurrentClassLogger();

    [Test]
    [TestCase(100, 44)]
    [TestCase(4000000, 4613732)]
    public void Should(int border, int expected)
    {
        // prepare
        Problem0002 sut = Scope.Resolve<Problem0002>();

        // run
        int result = sut.Solve(border);

        // verify
        Assert.AreEqual(expected, result);
    }

    [Test]
    [TestCase(4000000)]
    public void Solve(int border)
    {
        // prepare
        Problem0002 sut = Scope.Resolve<Problem0002>();

        // run
        int result = sut.Solve(border);

        Logger.Info("################");
        Logger.Info("# Problem was solved");
        Logger.Info($"# Result: {result}");
        Logger.Info("################");
    }
}
